### ISSUE TITLE
Format of coverage report

### ISSUE THREAD

**Issue by DarkLight1337** [CastleLab/COMP5111-Spring2023-Student-Assignments#3]
With reference to the requirements:

> ### Program output:
> For each coverage criterion (Task2, Task3, and Bonus Task), your program needs to generate a report file, which at least contains the following:
> 
> 1. The coverage of each statement/branch/line (statement/branch/line, yes or no).
> 2. The coverage for each class (percentage), including inner classes.

I would like to ask whether we can show the statement/branch in the form of Jimple code, or do we need to somehow extract the corresponding portion of the original source code?

**Comment by maybeLee** [comment]
It is fine to show the statement/branch in the form of Jimple code. You don't need to convert the Jimple code back to the source code.

**Comment by DarkLight1337** [comment]
Understood, thanks for the quick reply!
