### ISSUE TITLE
How close should the coverage be with the given example??

### ISSUE THREAD

**Issue by hchoaf** [CastleLab/COMP5111-Spring2023-Student-Assignments#4]
I tried to cross-check my instrumentation using the provided test suite, and the coverage result is slightly different from the provided results. Is it normal to have different coverage percentages with the same test suite? The overall coverage percentages are similar but some coverage percentages of the inner classes differ a lot (~20%)

**Comment by maybeLee** [comment]
Hi, your implementation result should be close (<2~3%) or even the same as our provided ones. The 20% difference indicates that the implementation may have some issues. Please see if you can check the implementation and refine it.
