### ISSUE TITLE
How to Get the Unit Test List of a Test Suite in Programmatical Way

### ISSUE THREAD

**Issue by VegZzz** [CastleLab/COMP5111-Spring2023-Student-Assignments#5]
Hi! May I know how to get the list of unit test inside a test suite class in programmatical way, such that we can run them seperately instead of running the whole test suite together?

**Comment by maybeLee** [comment]
If you feel this function necessary, you may use the org.junit.runner.Request class (see: https://junit.org/junit4/javadoc/4.12/org/junit/runner/Request.html). 

Here is the example code snippet to get all test cases in the test suite class `testClass`:

```Java
// Create a request for the test suite class
Request request = Request.aClass(testClass);

// Get the runner for the test suite class
Runner runner = request.getRunner();

// Print the names of all test cases in the suite
for (org.junit.runner.Description description : runner.getDescription().getChildren()) {
    System.out.println(description.getMethodName());
}
```

Here is the example code snippet to run the single test method inside `testClass`:

```Java
// Create a Request object that specifies the test case you want to run
Request request = Request.method(testClass, "testMethod");

// Run the test case and get the result
Result result = junit.run(request);
```
