### ISSUE TITLE
Assignment 2 Alternative IDEs

### ISSUE THREAD

**Issue by txaty** [CastleLab/COMP5111-Spring2023-Student-Assignments#7]
I am writing to ask if it is allowed to use althernative IDEs such as IntelliJ IDEA to perform Task 1, Assignment 2.
I've been trying getting the test results in Eclipse for enumours times but still facing errors.
However, I can successfully conduct the tests on IntelliJ IDEA and get the branch/line coverage of ```comp5111.assignment.cut.Subject``` (on Linux, with Java 11 SE).
Thanks.

**Comment by maybeLee** [comment]
It is fine to use an alternative IDEs as long as you provide the detailed instructions to reproduce your coverage result.
