### ISSUE TITLE
line number in the fault report

### ISSUE THREAD

**Issue by Eason51** [CastleLab/COMP5111-Spring2023-Student-Assignments#8]
I wonder should the fault report focus on the fault within the java source code or the jimple code. Since, a fault in a line of java source code may corresponds to multiple jimple statements, and these jimple statements may have different suspicious scores and rankings. In addition, should the fault report have the suspicious scor and ranking from each of the 6 testsuites spectrum report?

**Comment by maybeLee** [comment]
In our course, the statement refers to the jimple code. Therefore, we suggest your fault report focus on the fault inside the Jimple code. If you implement your fault report on the line inside java source code and you don't have time to switch to jimple statement, don't worry, we will grade your report based on the java source code.

**Comment by Eason51** [comment]
Thanks.
